-- Limpiar datos existentes para asegurar la idempotencia
DELETE FROM tbMapeoCampos;

-- Insertar los mapeos para la plantilla "PC" (F4203.11)
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'refContratoInspeccionOficial', NULL, 'Parte0_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'refSuministrador', NULL, 'Parte0_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'suministradorNombreDir', NULL, 'Parte1_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'objetoContrato', NULL, 'Parte1_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'descripcionMaterialAfectado', NULL, 'Parte1_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'numPlanoEspecificacion', NULL, 'Parte1_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'descripcionPropuestaCambio', NULL, 'Parte1_5');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'descripcionPropuestaCambioCont', NULL, 'Parte1_5Cont');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoCorregirDeficiencias', 'True', 'Parte1_6_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoMejorarCapacidad', 'True', 'Parte1_6_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoAumentarNacionalizacion', 'True', 'Parte1_6_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoMejorarSeguridad', 'True', 'Parte1_6_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoMejorarFiabilidad', 'True', 'Parte1_6_5');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoMejorarCosteEficacia', 'True', 'Parte1_6_6');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoOtros', 'True', 'Parte1_6_7');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'motivoOtrosDetalle', NULL, 'Parte1_6_8');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaCoste', 'Aumentará', 'Parte1_7a_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaCoste', 'Disminuirá', 'Parte1_7a_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaCoste', 'No variará', 'Parte1_7a_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaPlazo', 'Aumentará', 'Parte1_7b_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaPlazo', 'Disminuirá', 'Parte1_7b_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaPlazo', 'No variará', 'Parte1_7b_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaSeguridad', 'True', 'Parte1_7c_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaFiabilidad', 'True', 'Parte1_7c_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaMantenibilidad', 'True', 'Parte1_7c_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaIntercambiabilidad', 'True', 'Parte1_7c_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaVidaUtilAlmacen', 'True', 'Parte1_7c_5');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'incidenciaFuncionamientoFuncion', 'True', 'Parte1_7c_6');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'cambioAfectaMaterialEntregado', 'True', 'Parte1_9_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'cambioAfectaMaterialPorEntregar', 'True', 'Parte1_9_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'firmaOficinaTecnicaNombre', NULL, 'Parte1_10');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'firmaRepSuministradorNombre', NULL, 'Parte1_11');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'observacionesRACRef', NULL, 'Parte2_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'racCodigo', NULL, 'Parte2_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'observacionesRAC', NULL, 'Parte2_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'fechaFirmaRAC', NULL, 'Parte2_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'obsAprobacionAutoridadDiseno', NULL, 'Parte3_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'firmaAutoridadDisenoNombreCargo', NULL, 'Parte3_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'fechaFirmaAutoridadDiseno', NULL, 'Parte3_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'decisionFinal', 'APROBADO', 'Parte3_2_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'decisionFinal', 'NO APROBADO', 'Parte3_2_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'obsDecisionFinal', NULL, 'Parte3_3_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'cargoFirmanteFinal', NULL, 'Parte3_3_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('PC', 'fechaFirmaDecisionFinal', NULL, 'Parte3_3_3');

-- Insertar los mapeos para la plantilla "CDCA" (F4203.10)
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'refSuministrador', NULL, 'Parte0_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'numContrato', NULL, 'Parte1_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'identificacionMaterial', NULL, 'Parte1_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'numPlanoEspecificacion', NULL, 'Parte1_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'cantidadPeriodo', NULL, 'Parte1_5a');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'numSerieLote', NULL, 'Parte1_5b');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'descripcionImpactoNC', NULL, 'Parte1_6');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'refDesviacionesPrevias', NULL, 'Parte1_7');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'causaNC', NULL, 'Parte1_8');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'impactoCoste', 'Increased / aumentado', 'Parte1_9_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'impactoCoste', 'Decreased / disminuido', 'Parte1_9_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'impactoCoste', 'Unchanged / sin cambio', 'Parte1_9_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'clasificacionNC', 'Major / Mayor', 'Parte1_10_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'clasificacionNC', 'Minor / Menor', 'Parte1_10_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'requiereModificacionContrato', 'True', 'Parte1_12_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'efectoFechaEntrega', NULL, 'Parte1_13');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'identificacionAutoridadDiseno', NULL, 'Parte1_14');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'esSuministradorAD', 'True', 'Parte1_18_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'esSuministradorAD', 'False', 'Parte1_18_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'descripcionImpactoNCCont', NULL, 'Parte1_20');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'racRef', NULL, 'Parte2_21_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'racCodigo', NULL, 'Parte2_21_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'observacionesRAC', NULL, 'Parte2_21_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'fechaFirmaRAC', NULL, 'Parte2_22');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'decisionFinal', 'APROBADO', 'Parte3_23_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'decisionFinal', 'NO APROBADO', 'Parte3_23_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'observacionesFinales', NULL, 'Parte3_24_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'fechaFirmaDecisionFinal', NULL, 'Parte3_24_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCA', 'cargoFirmanteFinal', NULL, 'Parte3_24_4');

-- Insertar los mapeos para la plantilla "CDCASUB" (F4203.101)
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'refSuministrador', NULL, 'Parte0_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'refSubSuministrador', NULL, 'Parte0_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'suministradorPrincipalNombreDir', NULL, 'Parte1_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'subSuministradorNombreDir', NULL, 'Parte1_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'identificacionMaterial', NULL, 'Parte1_5');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'numPlanoEspecificacion', NULL, 'Parte1_6');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'cantidadPeriodo', NULL, 'Parte1_7a');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'numSerieLote', NULL, 'Parte1_7b');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'descripcionImpactoNC', NULL, 'Parte1_8');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'refDesviacionesPrevias', NULL, 'Parte1_9');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'causaNC', NULL, 'Parte1_10');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'impactoCoste', 'Incrementado', 'Parte1_11_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'impactoCoste', 'Sin cambio', 'Parte1_11_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'impactoCoste', 'Disminuido', 'Parte1_11_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'clasificacionNC', 'Mayor', 'Parte1_12_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'clasificacionNC', 'Menor', 'Parte1_12_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaPrestaciones', 'True', 'Parte1_13_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaSeguridad', 'True', 'Parte1_13_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaFiabilidad', 'True', 'Parte1_13_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaVidaUtil', 'True', 'Parte1_13_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaMedioambiente', 'True', 'Parte1_13_5');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaIntercambiabilidad', 'True', 'Parte1_13_6');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaMantenibilidad', 'True', 'Parte1_13_7');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaApariencia', 'True', 'Parte1_13_8');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'afectaOtros', 'True', 'Parte1_13_9');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'requiereModificacionContrato', 'True', 'Parte1_14');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'efectoFechaEntrega', NULL, 'Parte1_15');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'identificacionAutoridadDiseno', NULL, 'Parte1_16');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'esSubSuministradorAD', 'True', 'Parte1_20_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'esSubSuministradorAD', 'False', 'Parte1_20_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'nombreRepSubSuministrador', NULL, 'Parte1_21');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'descripcionImpactoNCCont', NULL, 'Parte1_22');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'racRef', NULL, 'Parte2_23_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'racCodigo', NULL, 'Parte2_23_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'observacionesRAC', NULL, 'Parte2_23_3');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'fechaFirmaRAC', NULL, 'Parte2_25');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'decisionSuministradorPrincipal', 'APROBADO', 'Parte3_26_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'decisionSuministradorPrincipal', 'NO APROBADO', 'Parte3_26_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'obsSuministradorPrincipal', NULL, 'Parte3_27_1');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'fechaFirmaSuministradorPrincipal', NULL, 'Parte3_27_2');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'firmaSuministradorPrincipalNombreCargo', NULL, 'Parte3_27_4');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'obsRACDelegador', NULL, 'Parte4_28');
INSERT INTO tbMapeoCampos (nombrePlantilla, nombreCampoTabla, valorAsociado, nombreCampoWord) VALUES ('CDCASUB', 'fechaFirmaRACDelegador', NULL, 'Parte4_30');