Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit


Public Function GetUserRole(ByVal userEmail As String) As UserRole
End Function

Public Function AuthenticateUser(ByVal userEmail As String, ByVal password As String) As Boolean
End Function

Public Function GetCurrentUserEmail() As String
End Function