Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit


Public Function ObtenerExpedientePorId(ByVal idExpediente As Long) As EExpediente
End Function

Public Function ObtenerExpedientePorNemotecnico(ByVal Nemotecnico As String) As EExpediente
End Function

Public Function ObtenerExpedientesParaSelector() As Object
End Function