VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAuthService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

' Contrato para obtener el rol de un usuario a partir de su email.
Public Function GetUserRole(ByVal UserEmail As String) As E_UserRole
End Function












